version: '2'

services:
  broker:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
  influx:
    image: influxdb
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    depends_on:
      - influx
  script:
    build: .
    depends_on:
      - influx
      - broker
